<div id="block-shipping"
     class="block shipping"
     data-mage-init='{"collapsible":{"openedState": "active", "saveState": true}}'>
    <div class="title" data-role="title">
        <strong id="block-shipping-heading" role="heading" aria-level="2">
            <?= $block->getQuote()->isVirtual() ?
                /** @noEscape */ __('Estimate Tax')
                : /** @noEscape */ __('Estimate Shipping and Tax') ?>
        </strong>
        <i class="icon-close"></i>
    </div>
    <div id="block-summary"
         data-bind="scope:'block-summary'"
         class="content"
         data-role="content"
         aria-labelledby="block-shipping-heading">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#block-summary": {
                    "Magento_Ui/js/core/app": <?= /** @noEscape */ $block->getJsLayout() ?>
                }
            }
        </script>
        <script> <?php // @codingStandardsIgnoreLine - MUST BEREFACTORED ?>
            window.checkoutConfig = <?= /** @noEscape */ $block->getSerializedCheckoutConfig() ?>;
            window.customerData = window.checkoutConfig.customerData;
            window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
            require([
                'mage/url',
                'Magento_Ui/js/block-loader'
            ], function(url, blockLoader) {
                blockLoader("<?= /** @noEscape */ $block->getViewFileUrl('images/loader-svg.svg') ?>");
                return url.setBaseUrl('<?= /** @noEscape */ $block->getBaseUrl() ?>');
            })
        </script>
    </div>
</div>
