<?php $welcomeMessage = $block->getWelcome(); ?>
<?php if ($block->getShowPart() == 'welcome') : ?>
    <li class="greet welcome" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <span class="logged-in"
              data-bind="text: new String('<?=
              $block->escapeHtml(__('Welcome, %1!', '%1'))
              ?>').replace('%1', customer().fullname)">
        </span>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <?= $block->getBlockHtml('header.additional') ?>
        <!-- /ko -->
    </li>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
<?php elseif ($block->getShowPart() == 'other') : ?>
    <?= $block->getChildHtml() ?>
<?php endif; ?>
<script type="text/x-magento-init">
{
    "*": {
        "ui-toggle": {
            "trigger":      ".js-toggle__title",
            "target":       ".js-toggle__content",
            "triggerEvent": "click",
            "UIUpdateable": "false",
            "overlay":      "true",
            "overlayElem":  ".js-toggle__overlay",
            "closeEnabled": "true",
            "close":        ".block-search__close"
        },
        "form-labels": {}
    },
    ".page-header": {
        "sticky-header": ""
    }
}
</script>
