<?php
$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')) :?>
    <div class="sections <?= /** @noEscape */ $groupCss ?>">
        <?php $layout = $block->getLayout(); ?>
        <div class="section-items <?= /** @noEscape */ $groupCss ?>-items"
             data-mage-init='<?= /** @noEscape */ $groupBehavior ?>'>
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                    $html = $layout->renderElement($name);
                if (!trim($html) && ($block->getUseForce() != true)) {
                    continue;
                }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="section-item-title <?= /** @noEscape */ $groupCss ?>-item-title" data-role="collapsible">
                    <a class="<?= /** @noEscape */ $groupCss ?>-item-switch"
                       data-toggle="switch"
                       href="#<?= /** @noEscape */ $alias ?>">
                        <?= /** @noEscape */ $label ?>
                    </a>
                </div>
                <div class="section-item-content <?= /** @noEscape */ $groupCss ?>-item-content"
                     id="<?= /** @noEscape */ $alias ?>"
                     data-role="content">
                    <?= /** @noEscape */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
    <div class="overlay off-canvas-overlay"><span data-action="toggle-nav" class="action nav-toggle drawer show-for-small-only nav-close asd"><i class="icon-manu"></i></span></div>
<?php endif; ?>
