<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= /** @noEscape */ $block->getViewFileUrl('images/loader-svg.svg') ?>"
                 alt="<?= /** @noEscape */ __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /** @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script> <?php // @codingStandardsIgnoreLine - MUST BEREFACTORED ?>
        window.checkoutConfig = <?= /** @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script> <?php // @codingStandardsIgnoreLine - MUST BEREFACTORED ?>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= /** @noEscape */ $block->getViewFileUrl('images/loader-svg.svg') ?>");
            return url.setBaseUrl('<?= /** @noEscape */ $block->getBaseUrl() ?>');
        })
    </script>
</div>
