<?php
/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('YOU MAY ALSO LIKE');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
?>

<?php if ($exist):?>

<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<div class="block <?= /** @noEscape */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /** @noEscape */ $limit ?>" data-shuffle="<?= /** @noEscape */ $shuffle ?>">
    <?php else: ?>
    <div class="block <?= /** @noEscape */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /** @noEscape */ $limit ?>" data-shuffle="<?= /** @noEscape */ $shuffle ?>">
        <?php endif; ?>
        <?php else: ?>
        <div class="block <?= /** @noEscape */ $class ?>">
            <?php endif; ?>
            <div class="block-title title block-title--centered">
                <strong id="block-<?= /** @noEscape */ $class ?>-heading" role="heading" aria-level="2"><?= /** @noEscape */ $title ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= /** @noEscape */ $class ?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart): ?>
                    <div class="block-actions">
                        <?= /** @noEscape */ __('Check items to add to the cart or') ?>
                        <button type="button" class="action select" role="select-all"><span><?= /** @noEscape */ __('select all') ?></span></button>
                    </div>
                <?php endif; ?>
                <div class="swiper-container swiper-carousel swiper-container-upsell is-loading products wrapper">
                    <div class="products list items swiper-wrapper">
                        <?php foreach ($items as $_item): ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>

                            <div class="swiper-slide product-item item product">
                                <div class="product-item-info <?= /** @noEscape */ $available ?>">
                                    <?= /** @noEscape */ '<!-- ' . $image . '-->' ?>
                                    <a href="<?= /** @noEscape */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product details product-item-details">
                                        <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /** @noEscape */ $block->getProductUrl($_item) ?>">
                                                <?= $block->escapeHtml($_item->getName()) ?></a>
                                        </strong>
                                        <div class="product-item-details__price-wrapper">
                                            <?= /** @noEscape */ $block->getProductPrice($_item) ?>
                                        </div>


                                        <?php if ($templateType): ?>
                                            <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif; ?>

                                        <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                            <?php if (!$_item->getRequiredOptions()): ?>
                                                <div class="field choice related">
                                                    <input type="checkbox" class="checkbox related" id="related-checkbox<?= /** @noEscape */ $_item->getId() ?>" name="related_products[]" value="<?= /** @noEscape */ $_item->getId() ?>" />
                                                    <label class="label" for="related-checkbox<?= /** @noEscape */ $_item->getId() ?>"><span><?= /** @noEscape */ __('Add to Cart') ?></span></label>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                        <?php if ($showAddTo || $showCart): ?>
                                            <div class="product actions product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /** @noEscape */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /** @noEscape */ __('Add to Cart') ?>">
                                                                    <span><?= /** @noEscape */ __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary"
                                                                        data-post='<?= /** @noEscape */ $postData ?>'
                                                                        type="button" title="<?= /** @noEscape */ __('Add to Cart') ?>">
                                                                    <span><?= /** @noEscape */ __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available"><span><?= /** @noEscape */ __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?= /** @noEscape */ __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>

                                                <?php if ($showAddTo): ?>
                                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                            <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <div class="actions">
                                        <button class="view-details">View details</button>

                                        <i class="icon-whishlist"></i>
                                        <i class="icon-compare"></i>

                                    </div>
                                </div>
                            </div>
                        <?php endforeach ?>
                    </div>
                    <div class="swiper-pagination"></div>
                    <!-- Add Arrows -->
                    <div class="swiper-button-next icon-right-indicator"></div>
                    <div class="swiper-button-prev icon-left-indicator"></div>
                </div>
            </div>
        </div>

        <script type="text/javascript" xml="space">
            // <![CDATA[
            require([
                'jquery',
                'swiper'
            ], function ($, Swiper) {
                new Swiper('.swiper-container-upsell', {
                    spaceBetween: 24,
                    slidesPerView: 1,
                    navigation: {
                        nextEl: '.swiper-container-upsell .swiper-button-next',
                        prevEl: '.swiper-container-upsell .swiper-button-prev',
                    },
                    breakpoints: {
                        540: {
                            slidesPerView: 1,
                        },
                        768: {
                            slidesPerView: 3,
                        },
                        1024: {
                            slidesPerView: 4,
                        }
                    },
                    on: {
                        init: function () {
                            $('.swiper-container-upsell').removeClass('is-loading');
                        }
                    },
                    pagination: {
                        el: '.swiper-pagination',
                    }
                });
            });
            // ]]>
        </script>
        <?php endif;?>
