<span class="product-image-container"
      style="width:<?= /** @noEscape */ $block->getWidth() ?>px;">
    <span class="product-image-wrapper iuu"
        <img class="lazyload <?= /** @noEscape */ $block->getClass() ?>"
            <?= /** @noEscape */ $block->getCustomAttributes() ?>
            data-src="<?= /** @noEscape */ $block->getImageUrl(); ?>"
             src="<?= /** @noEscape */ $block->getViewFileUrl('images/blank.png')?>"
             max-width="<?= /** @noEscape */ $block->getWidth() ?>"
             max-height="<?= /** @noEscape */ $block->getHeight() ?>"
             alt="<?= /** @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>"/></span>
</span>
