<script type="text/x-magento-init">
    {
        ".header.links": {
            "header-account-links": {
                "mobileParent": "#store\\.links",
                "desktopParent": ".top-links__wrapper",
                "breakpoint": "(min-width: 768px)",
                "cssClass": "js-toggle__content js-toggle__content--animated positioned--right"
            }
        }
    }
</script>
